name: Build

on:
  push:
    branches: [main]
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore tools
        run: dotnet tool restore
      - name: Run the build script
        uses: cake-build/cake-action@v1
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          NUGET_API_URL: https://api.nuget.org/v3/index.json
        with:
          target: Publish